routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Backend\EditPasswordController;
use App\Http\Controllers\Backend\EditProfileController;
use App\Http\Controllers\Backend\HomeController;
use App\Http\Controllers\Backend\ManageCourseController;
use App\Http\Controllers\Backend\ManageUserController;
use App\Http\Controllers\Backend\ReportTokenPlayGameController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Backend
Route::group(['prefix' => 'backend', 'as' => 'backend.'], function() {

    // Auth
    Auth::routes();

    // After Login go to Home
    Route::get('/', [HomeController::class, 'home']);

    // Edit Profile
    Route::get('edit-profile', [EditProfileController::class, 'edit'])->name('edit.profile');
    Route::post('update-profile', [EditProfileController::class, 'update'])->name('update.profile');

    // Edit Password
    Route::get('edit-password', [EditPasswordController::class, 'edit'])->name('edit.password');
    Route::post('update-password', [EditPasswordController::class, 'update'])->name('update.password');

    // Middleware Check SuperAdmin
    Route::group(['middleware' => ['checkAuthUser:superadmin']], function () {
        // Route::resource('/manage-users', ManageUserController::class);
    });

    // Middleware Check SuperAdmin or Admin
    Route::group(['middleware' => ['checkAuthUser:superadmin|admin']], function () {
        // Report Token Access & Play Games
        Route::resource('/report-token-play-games', ReportTokenPlayGameController::class);
        Route::post('/report-token-play-games-export', [ReportTokenPlayGameController::class, "export"])->name('report.token.play.games.export');
    });
});

// Website Game Portal
Route::group(['prefix' => '', 'as' => 'website.'], function () {

    // Check Encrypted String, Redirect to Home Page
    Route::get('/c', [App\Http\Controllers\HomeController::class, 'convertEncryptedRedirectToHomePage']);
    // Home Page
    Route::get('', [App\Http\Controllers\HomeController::class, 'homePage'])->name('home.page');
    // All Game Page
    Route::get('/allgames', [App\Http\Controllers\GameController::class, 'allGamePage'])->name('all.game.page');
    // Preview Game Page
    Route::get('/preview/{slugUrl}', [App\Http\Controllers\GameController::class, 'previewGamePage'])->name('preview.game.page');
    // All Play Game Page
    Route::get('/play/{slugUrl}', [App\Http\Controllers\GameController::class, 'playGamePage'])->name('play.game.page');

    Route::get('/check/session', function() {
        return session()->all();
    });

    Route::get('/delete/session', function() {
        return session()->flush();
    });
});

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;

class Game extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'games';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'category' => 'array',
    ];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    public function getNameLimitAttribute() {

        return Str::limit($this->name, 14);
    }

    public function scopeFilter(Builder $query, $category, $status_popular, $status_free) {

        if ($category) {
            $query->whereJsonContains('category', $category);
        }
        if ($status_popular) {
            $query->where('status_popular', $status_popular);
        }
        if ($status_free) {
            $query->where('status_free', $status_free);
        }
    }

    /**
     * Scope a query to only include active partners.
     */
    public function scopePopular(Builder $query): void
    {
        $query->where('status_popular', config('constants.status_popular.active'));
    }

    /**
     * Scope a query to only include inactive partners.
     */
    public function scopeNotPopular(Builder $query): void
    {
        $query->where('status_popular', config('constants.status_popular.inactive'));
    }

    /**
     * Scope a query to only include active partners.
     */
    public function scopeFree(Builder $query): void
    {
        $query->where('status_free', config('constants.status_free.active'));
    }

    /**
     * Scope a query to only include inactive partners.
     */
    public function scopeNotFree(Builder $query): void
    {
        $query->where('status_free', config('constants.status_free.inactive'));
    }

    /**
     * Scope a query to only include active partners.
     */
    public function scopeActive(Builder $query): void
    {
        $query->where('status', config('constants.status.active'));
    }

    /**
     * Scope a query to only include inactive partners.
     */
    public function scopeInActive(Builder $query): void
    {
        $query->where('status', config('constants.status.inactive'));
    }
}

resources/views/all-games.blade.php
@extends('layouts.template')
@section('title', 'เกมออนไลน์ Hype เกมส์- เล่นเลยตอนนี้!')
@section('content')
    <br/>
    <br/>

    <div id="shop-section" class="item-center">
        <iframe src="{{ asset('assets/magazine/index.html') }}" title="TOP IMAGE"></iframe>
    </div>

    <!-- shop-section2
        ================================================== -->
    <section id="shop-section2">
        <div class="container">
            <div class="tab-product-box">
                <div class="title-line">
                    <h1>All Games<a href="#">View All</a></h1>
                </div>
                <!-- Nav tabs -->
                <div class="tab-posts-box">
                    <div class="tab-content">
                        <div class="tab-pane active" id="option1">
                            <div class="row">
                                @foreach ($all_games as $all_game)
                                    <div class="col-md-4">
                                        <ul class="product-list">
                                            <li>
                                                <img src="{{ asset('games/'.$all_game->thumbnail_image) }}" alt="" width="100px">
                                                <div class="product-list-content">
                                                    <h2><a href="{{ route('website.preview.game.page', ['slugUrl' => $all_game->slug_url]) }}">{{ $all_game->name_limit }}</a></h2>
                                                    <p>
                                                        @for ($start_rating=1; $start_rating<=5; $start_rating++)
                                                            @if ($start_rating <= $all_game->rating)
                                                                <i class="fa fa-star"></i>
                                                            @else
                                                                <i class="fa fa-star-o"></i>
                                                            @endif
                                                        @endfor
                                                    </p>
                                                    <span><i class="fa fa-eye"></i> {{ number_format($all_game->count_views) }}<i class="fa fa-user" style="padding-left: 15px;"></i> {{ number_format($all_game->count_plays) }}</span>
                                                    <div class="product-links">
                                                        <a class="add-cart-btn" href="{{ route('website.preview.game.page', ['slugUrl' => $all_game->slug_url]) }}"><i class="fa fa-play"></i><span>PLALY NOW</span></a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End shop section2 -->
@endsection

resources/views/home.blade.php
@extends('layouts.template')
@section('title', 'เกมออนไลน์ Hype เกมส์- เล่นเลยตอนนี้!')
@section('content')
    <br/>
    <br/>
    <div id="shop-section" class="item-center">
        <iframe src="{{ asset('assets/magazine/index.html') }}" title="TOP IMAGE"></iframe>
    </div>

	<!-- shop-section
		================================================== -->
	<div id="shop-section">
		<div class="container">
			<div class="title-section">
				<h1>Most Popular Games</h1>
				<span></span>
			</div>
			<div class="title-line">
				<h1>Top<a href="{{ route('website.all.game.page', ['status_popular' => config('constants.status_popular.active')]) }}">View All</a></h1>
			</div>
			<div class="products-box">
				<div class="carousel-arrows owl-arrows">
					<a href="#" class="prev-link"><i class="fa fa-chevron-left"></i></a>
					<a href="#" class="next-link"><i class="fa fa-chevron-right"></i></a>
				</div>
				<div id="owl-demo-pro" class="owl-carousel">
                    @foreach ($popular_games as $popular_game)
                        <div class="item product-post">
                            <h2><a href="{{ route('website.preview.game.page', ['slugUrl' => $popular_game->slug_url]) }}">{{ $popular_game->name }}</a></h2>
                            <p>
                                @for ($start_rating=1; $start_rating<=5; $start_rating++)
                                    @if ($start_rating <= $popular_game->rating)
                                        <i class="fa fa-star"></i>
                                    @else
                                        <i class="fa fa-star-o"></i>
                                    @endif
                                @endfor
                            </p>
                            <span><i class="fa fa-eye"></i> {{ number_format($popular_game->count_views) }}<i class="fa fa-user" style="padding-left: 15px;"></i> {{ number_format($popular_game->count_plays) }}</span>
                            <div class="gal-product">
                                <img src="{{ asset('games/'.$popular_game->thumbnail_image) }}" alt="" width="50px">
                            </div>
                            <div class="product-links">
                                <a class="add-cart-btn" href="{{ route('website.preview.game.page', ['slugUrl' => $popular_game->slug_url]) }}"><i class="fa fa-play"></i><span>PLALY NOW</span></a>
                            </div>
                        </div>
                    @endforeach
				</div>
			</div>
		</div>
		<!-- shop-section -->

		<!-- shop-section2
			================================================== -->
		<section id="shop-section2">
			<div class="container">
				<div class="tab-product-box">
					<div class="title-line">
					    <h1>Free Games<a href="{{ route('website.all.game.page', ['status_free' => config('constants.status_free.active')]) }}">View All</a></h1>
					</div>
					<!-- Nav tabs -->
					<div class="tab-posts-box">
						<div class="tab-content">
							<div class="tab-pane active" id="option1">
								<div class="row">
                                    @foreach ($free_games as $free_game)
                                        <div class="col-md-4">
                                            <ul class="product-list">
                                                <li>
                                                    <img src="{{ asset('games/'.$free_game->thumbnail_image) }}" alt="" width="100px">
                                                    <div class="product-list-content">
                                                        <h2><a href="{{ route('website.preview.game.page', ['slugUrl' => $free_game->slug_url]) }}">{{ $free_game->name_limit }}</a></h2>
                                                        <p>
                                                            @for ($start_rating=1; $start_rating<=5; $start_rating++)
                                                                @if ($start_rating <= $free_game->rating)
                                                                    <i class="fa fa-star"></i>
                                                                @else
                                                                    <i class="fa fa-star-o"></i>
                                                                @endif
                                                            @endfor
                                                        </p>
                                                        <span>
                                                        <i class="fa fa-eye"></i> {{ number_format($free_game->count_views) }}<i class="fa fa-user" style="padding-left: 15px;"></i> {{ number_format($free_game->count_plays) }}</span>
                                                        <div class="product-links">
                                                            <a class="add-cart-btn" href="{{ route('website.preview.game.page', ['slugUrl' => $free_game->slug_url]) }}"><i class="fa fa-play"></i><span>PLALY NOW</span></a>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    @endforeach
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End shop section2 -->

		<!-- shop-section2
			================================================== -->
		<section id="shop-section2">
			<div class="container">
				<div class="tab-product-box">
					<div class="title-line">
					    <h1>All Games<a href="{{ route('website.all.game.page') }}">View All</a></h1>
					</div>
					<!-- Nav tabs -->
					<div class="tab-posts-box">
						<div class="tab-content">
							<div class="tab-pane active" id="option1">
								<div class="row">
                                    @foreach ($all_games as $all_game)
                                        <div class="col-md-4">
                                            <ul class="product-list">
                                                <li>
                                                    <img src="{{ asset('games/'.$all_game->thumbnail_image) }}" alt="" width="100px">
                                                    <div class="product-list-content">
                                                        <h2><a href="{{ route('website.preview.game.page', ['slugUrl' => $all_game->slug_url]) }}">{{ $all_game->name_limit }}</a></h2>
                                                        <p>
                                                            @for ($start_rating=1; $start_rating<=5; $start_rating++)
                                                                @if ($start_rating <= $all_game->rating)
                                                                    <i class="fa fa-star"></i>
                                                                @else
                                                                    <i class="fa fa-star-o"></i>
                                                                @endif
                                                            @endfor
                                                        </p>
                                                        <span><i class="fa fa-eye"></i> {{ number_format($all_game->count_views) }}<i class="fa fa-user" style="padding-left: 15px;"></i> {{ number_format($all_game->count_plays) }}</span>
                                                        <div class="product-links">
                                                            <a class="add-cart-btn" href="{{ route('website.preview.game.page', ['slugUrl' => $all_game->slug_url]) }}"><i class="fa fa-play"></i><span>PLALY NOW</span></a>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    @endforeach
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End shop section2 -->
@endsection

resources/views/play-game.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>เกมออนไลน์ Hype Game - {{ $game->name }}</title>
    <style>
    html, body {
        margin: 0; padding: 0; border-width: 0; height: 100%;
    }
    html, body {
        overflow: hidden;
    }
    /* overflow: hidden because we don't want browser to show its scrollbars. */
    #application_area {
        height: 100%; width: 100%;
    }
    </style>

    <!-- favicon -->
    {{-- <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff"> --}}

</head>
<body>
    <!-- https://hydrangeacoffee.com/game%20portal/ -->
    <iframe id="application_area" src="/games/{{ $game->path_game }}" frameborder="0" scrolling="yes"></iframe>
    </iframe>
</body>
</html>

resources/views/preview-game.blade.php
@extends('layouts.template')
@section('title', 'เกมออนไลน์ Hype Game - '.$game->name)
@section('content')

<div id="content">
    <section class="single-project-section">
        <div class="container">
            <div class="title-project">
                <h1>{{ $game->name }}</h1>
            </div>
            <div class="project-gallery">
                <div class="flexslider">
                    <ul class="slides" style="list-style: none; padding: 0px;">
                        <li>
                            <img alt="" src="{{ asset('games/'.$game->thumbnail_image) }}" />
                        </li>
                    </ul>
                </div>
                {{-- <a class="likes" href="#"><i class="fa fa-heart-o"></i><span>15</span></a> --}}
            </div>
            <div class="project-content">
                <div class="row">
                    <div class="col-md-12">
                        <h2>About the game</h2>
                        <p>{{ $game->description }}</p>
                        <div>
                            <a class="viewgame" href="{{ route("website.play.game.page", ['slugUrl' => $game->slug_url]) }}"><i class="fa fa-play"></i><span style="padding-left:10px;">PLALY NOW</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End single-project -->

</div>
<!-- end content -->

<!-- shop-section2
    ================================================== -->
<section id="shop-section2">
    <div class="container">
        <div class="tab-product-box">
            <div class="title-line">
            <h1>Popular Games<a href="{{ route('website.all.game.page', ['status_popular' => config('constants.status_popular.active')]) }}">View All</a></h1>
            </div>
            <!-- Nav tabs -->
            <div class="tab-posts-box">
                <div class="tab-content">
                    <div class="tab-pane active" id="option1">
                        <div class="row">
                            @foreach ($popular_games as $popular_game)
                                <div class="col-md-4">
                                    <ul class="product-list">
                                        <li>
                                            <img src="{{ asset('games/'.$popular_game->thumbnail_image) }}" alt="" width="100px">
                                            <div class="product-list-content">
                                                <h2><a href="{{ route('website.preview.game.page', ['slugUrl' => $popular_game->slug_url]) }}">{{ $popular_game->name_limit }}</a></h2>
                                                <p>
                                                    @for ($start_rating=1; $start_rating<=5; $start_rating++)
                                                        @if ($start_rating <= $popular_game->rating)
                                                            <i class="fa fa-star"></i>
                                                        @else
                                                            <i class="fa fa-star-o"></i>
                                                        @endif
                                                    @endfor
                                                </p>
                                                <span><i class="fa fa-eye"></i> {{ number_format($popular_game->count_views) }}<i class="fa fa-user" style="padding-left: 15px;"></i> {{ number_format($popular_game->count_plays) }}</span>
                                                <div class="product-links">
                                                    <a class="add-cart-btn" href="{{ route('website.preview.game.page', ['slugUrl' => $popular_game->slug_url]) }}"><i class="fa fa-play"></i><span>PLALY NOW</span></a>
                                                </div>
                                            </div>
                                        </li>

                                    </ul>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End shop section2 -->
@endsection