routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Backend\EditPasswordController;
use App\Http\Controllers\Backend\EditProfileController;
use App\Http\Controllers\Backend\HomeController;
use App\Http\Controllers\Backend\ManageCourseController;
use App\Http\Controllers\Backend\ManageUserController;
use App\Http\Controllers\Backend\ReportTokenPlayGameController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Backend
Route::group(['prefix' => 'backend', 'as' => 'backend.'], function() {

    // Auth
    Auth::routes();

    // After Login go to Home
    Route::get('/', [HomeController::class, 'home']);

    // Edit Profile
    Route::get('edit-profile', [EditProfileController::class, 'edit'])->name('edit.profile');
    Route::post('update-profile', [EditProfileController::class, 'update'])->name('update.profile');

    // Edit Password
    Route::get('edit-password', [EditPasswordController::class, 'edit'])->name('edit.password');
    Route::post('update-password', [EditPasswordController::class, 'update'])->name('update.password');

    // Middleware Check SuperAdmin
    Route::group(['middleware' => ['checkAuthUser:superadmin']], function () {
        // Route::resource('/manage-users', ManageUserController::class);
    });

    // Middleware Check SuperAdmin or Admin
    Route::group(['middleware' => ['checkAuthUser:superadmin|admin']], function () {
        // Report Token Access & Play Games
        Route::resource('/report-token-play-games', ReportTokenPlayGameController::class);
        Route::post('/report-token-play-games-export', [ReportTokenPlayGameController::class, "export"])->name('report.token.play.games.export');
    });
});

// Website Game Portal
Route::group(['prefix' => '', 'as' => 'website.'], function () {

    // Check Encrypted String, Redirect to Home Page
    Route::get('/c', [App\Http\Controllers\HomeController::class, 'convertEncryptedRedirectToHomePage']);
    // Home Page
    Route::get('', [App\Http\Controllers\HomeController::class, 'homePage'])->name('home.page');
    // All Game Page
    Route::get('/allgames', [App\Http\Controllers\GameController::class, 'allGamePage'])->name('all.game.page');
    // Preview Game Page
    Route::get('/preview/{slugUrl}', [App\Http\Controllers\GameController::class, 'previewGamePage'])->name('preview.game.page');
    // All Play Game Page
    Route::get('/play/{slugUrl}', [App\Http\Controllers\GameController::class, 'playGamePage'])->name('play.game.page');

    Route::get('/check/session', function() {
        return session()->all();
    });

    Route::get('/delete/session', function() {
        return session()->flush();
    });
});

resources/views/backend/pages/profile/edit.blade.php
@extends('backend.layouts.template')
@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1></h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Edit</a></li>
                    <li class="breadcrumb-item active">Profile</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            @include('backend.components.notification')

            <div class="card card-warning">
                <div class="card-header">
                    <h3 class="card-title">Edit Profile</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>

                <!-- /.card-header -->
                <form action="{{ route('backend.update.profile') }}" method="post">
                    @csrf
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Email address</label>
                                    <input type="email" class="form-control" id="" placeholder="" value="{{ $user->email }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Full Name</label>
                                    @include('backend.components.required')
                                    <input type="text" name="name" class="form-control" id="" placeholder="" value="{{ old('name', $user->name) }}" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Position</label>
                                    <select class="form-control select2" name="" style="width: 100%;" disabled>
                                        @foreach (config('constants.position') as $position)
                                            <option value="{{ $position }}" @if($position == $user->position) selected @endif>{{ $position }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <!-- /.form-group -->
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Status</label>
                                    <select class="form-control select2" name="" style="width: 100%;" disabled>
                                        @foreach (config('constants.status') as $status)
                                            <option value="{{ $status }}" @if($status == $user->status) selected @endif>{{ $status }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <!-- /.form-group -->
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Created_at</label>
                                    <input type="text" class="form-control" id="" placeholder="" value="{{ $user->created_at }}" readonly>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</div>
@endsection