routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Backend\EditPasswordController;
use App\Http\Controllers\Backend\EditProfileController;
use App\Http\Controllers\Backend\HomeController;
use App\Http\Controllers\Backend\ManageCourseController;
use App\Http\Controllers\Backend\ManageUserController;
use App\Http\Controllers\Backend\ReportTokenPlayGameController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Backend
Route::group(['prefix' => 'backend', 'as' => 'backend.'], function() {

    // Auth
    Auth::routes();

    // After Login go to Home
    Route::get('/', [HomeController::class, 'home']);

    // Edit Profile
    Route::get('edit-profile', [EditProfileController::class, 'edit'])->name('edit.profile');
    Route::post('update-profile', [EditProfileController::class, 'update'])->name('update.profile');

    // Edit Password
    Route::get('edit-password', [EditPasswordController::class, 'edit'])->name('edit.password');
    Route::post('update-password', [EditPasswordController::class, 'update'])->name('update.password');

    // Middleware Check SuperAdmin
    Route::group(['middleware' => ['checkAuthUser:superadmin']], function () {
        // Route::resource('/manage-users', ManageUserController::class);
    });

    // Middleware Check SuperAdmin or Admin
    Route::group(['middleware' => ['checkAuthUser:superadmin|admin']], function () {
        // Report Token Access & Play Games
        Route::resource('/report-token-play-games', ReportTokenPlayGameController::class);
        Route::post('/report-token-play-games-export', [ReportTokenPlayGameController::class, "export"])->name('report.token.play.games.export');
    });
});

// Website Game Portal
Route::group(['prefix' => '', 'as' => 'website.'], function () {

    // Check Encrypted String, Redirect to Home Page
    Route::get('/c', [App\Http\Controllers\HomeController::class, 'convertEncryptedRedirectToHomePage']);
    // Home Page
    Route::get('', [App\Http\Controllers\HomeController::class, 'homePage'])->name('home.page');
    // All Game Page
    Route::get('/allgames', [App\Http\Controllers\GameController::class, 'allGamePage'])->name('all.game.page');
    // Preview Game Page
    Route::get('/preview/{slugUrl}', [App\Http\Controllers\GameController::class, 'previewGamePage'])->name('preview.game.page');
    // All Play Game Page
    Route::get('/play/{slugUrl}', [App\Http\Controllers\GameController::class, 'playGamePage'])->name('play.game.page');

    Route::get('/check/session', function() {
        return session()->all();
    });

    Route::get('/delete/session', function() {
        return session()->flush();
    });
});

app/Http/Controllers/Backend/EditPasswordController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class EditPasswordController extends Controller
{
    //
    public function edit () {

        return view('backend.pages.password.edit');
    }

    public function update (Request $request) {

        $validated = $request->validate([
            'password' => 'min:6|required_with:password_confirmation|same:password_confirmation',
            'password_confirmation' => 'min:6'
        ]);

        $data = [
            'password' => Hash::make($request->input('password'))
        ];

        User::where('id', Auth::user()->id)
            ->update($data);

        return redirect()->back()->with(['success' => 'Update Data Completed!']);
    }
}

app/Http/Controllers/Backend/EditProfileController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EditProfileController extends Controller
{
    //
    public function edit () {

        return view('backend.pages.profile.edit', [
            'user' => Auth::user()
        ]);
    }

    public function update (Request $request) {

        $validated = $request->validate([
            'name' => 'required',
        ]);

        $data = [
            'name' => $request->input('name')
        ];

        User::where('id', Auth::user()->id)
            ->update($data);

        return redirect()->back()->with(['success' => 'Update Data Completed!']);
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    //
    public function home() {
        if (Auth::check() && Auth::user()->position == config('constants.position.superadmin')) {
            return redirect()->route('backend.report-token-play-games.index');
        } else if (Auth::check() && Auth::user()->position == config('constants.position.admin')) {
            return redirect()->route('backend.report-token-play-games.index');
        }

        return redirect()->route('backend.login');
    }
}

app/Http/Controllers/Backend/ManageUserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ManageUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('backend.pages.manage-users.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ReportTokenPlayGameController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Exports\ReportTokenPlayGameExport;
use App\Http\Controllers\Controller;
use App\Models\Partner;
use App\Models\TokenPlayGame;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Carbon\Carbon;

class ReportTokenPlayGameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $partners = Partner::active()->get();

        return view('backend.pages.report-token-play-games.list', [
            'partners' => $partners
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function export(Request $request) {

        $validated = $request->validate([
            'partner_id' => 'required',
            'date_range' => 'sometimes',
        ]);

        list($start_date_time, $end_date_time) = convertDateRangeToStartDateTimeEndDateTime($request->input('date_range'));

        $token_play_games = TokenPlayGame::filters($request->input('partner_id'), $start_date_time, $end_date_time)->get();

        return Excel::download(new ReportTokenPlayGameExport($token_play_games), Carbon::now().'_tokens.xls');
    }
}

resources/views/backend/layouts/footer.blade.php
            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="float-right d-none d-sm-block">
                    <b>Version</b> 1.1.0
                </div>
                <strong>Copyright &copy; 2014-2021 <a href="#">{{ config('app.name') }}</a>.</strong> All rights reserved.
            </footer>

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
        <!-- ./wrapper -->

        <!-- jQuery -->
        <script src="{{ asset("assets/adminlte/plugins/jquery/jquery.min.js") }}"></script>
        <!-- Bootstrap 4 -->
        <script src="{{ asset("assets/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js") }}"></script>
        <!-- Select2 -->
        <script src="{{ asset("assets/adminlte/plugins/select2/js/select2.full.min.js") }}"></script>
        <!-- Bootstrap4 Duallistbox -->
        <script src="{{ asset("assets/adminlte/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js") }}"></script>
        <!-- InputMask -->
        <script src="{{ asset("assets/adminlte/plugins/moment/moment.min.js") }}"></script>
        <script src="{{ asset("assets/adminlte/plugins/inputmask/jquery.inputmask.min.js") }}"></script>
        <!-- date-range-picker -->
        <script src="{{ asset("assets/adminlte/plugins/daterangepicker/daterangepicker.js") }}"></script>
        <!-- bootstrap color picker -->
        <script src="{{ asset("assets/adminlte/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js") }}"></script>
        <!-- Tempusdominus Bootstrap 4 -->
        <script src="{{ asset("assets/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js") }}"></script>
        <!-- Bootstrap Switch -->
        <script src="{{ asset("assets/adminlte/plugins/bootstrap-switch/js/bootstrap-switch.min.js") }}"></script>
        <!-- BS-Stepper -->
        <script src="{{ asset("assets/adminlte/plugins/bs-stepper/js/bs-stepper.min.js") }}"></script>
        <!-- dropzonejs -->
        <script src="{{ asset("assets/adminlte/plugins/dropzone/min/dropzone.min.js") }}"></script>
        <!-- AdminLTE App -->
        <script src="{{ asset("assets/adminlte/dist/js/adminlte.min.js") }}"></script>
        <!-- AdminLTE for demo purposes -->
        <!--<script src="{{ asset("assets/adminlte/dist/js/demo.js") }}"></script>-->
        <!-- Page specific script -->
        <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
            theme: 'bootstrap4'
            })

            //Date range picker
            $('#reservation').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    format: 'YYYY-MM-DD',
                    cancelLabel: 'Clear'
                }
            })

            $('#reservation').on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.endDate.format('YYYY-MM-DD'));
            });

            $('#reservation').on('cancel.daterangepicker', function(ev, picker) {
                $(this).val('');
            });
        })
        </script>

        @yield('script')
    </body>
</html>

resources/views/backend/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name') }} | @yield('title')</title>
    <!-- Google Font:  Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/fontawesome-free/css/all.min.css") }}">
    <!-- daterange picker -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/daterangepicker/daterangepicker.css") }}">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css") }}">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css") }}">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css") }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/select2/css/select2.min.css") }}">
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css") }}">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css") }}">
    <!-- BS Stepper -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/bs-stepper/css/bs-stepper.min.css") }}">
    <!-- dropzonejs -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/plugins/dropzone/min/dropzone.min.css") }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset("assets/adminlte/dist/css/adminlte.min.css") }}">
    @yield('style')
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="ml-auto navbar-nav">
                <li class="nav-item dropdown user user-menu">
                    <a href="#" class="text-white nav-link dropdown-toggle btn btn-dark" data-toggle="dropdown">
                        <span class="hidden-xs">Setting</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="text-center">
                                <div class="pull-left" style="display:inline">
                                    <a href="{{ route('backend.edit.profile') }}" class="btn btn-info btn-flat">Profile</a>
                                </div>
                                <div class="pull-center" style="display:inline">
                                    <a href="{{ route('backend.edit.password') }}" class="btn btn-warning btn-flat">Password</a>
                                </div>
                                <div class="pull-right" style="display:inline">

                                    <a class="btn btn-danger btn-flat" href="{{ route('backend.logout') }}" onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                                        Sign out
                                    </a>

                                    <form id="logout-form" action="{{ route('backend.logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

    @include('backend.layouts.sidebar')

    @yield('content')

resources/views/backend/layouts/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="{{ asset('assets/adminlte/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Backend</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="pb-3 mt-3 mb-3 user-panel d-flex">
            <div class="image">
                <img src="{{ asset('assets/adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ \Auth::user()->name }}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                    <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @if (hasPermission(Auth::user()->position, "superadmin|admin"))
                    <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                    <li class="nav-item @if(request()->is('*/report*')) menu-open @endif">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-file-alt"></i>
                            <p>
                                Report
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ route('backend.report-token-play-games.index') }}" class="nav-link  @if(request()->is('*/report-token-play-games')) active @endif">
                                    <i class="fas fa-file nav-icon ml-3"></i>
                                    <p>Token</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

resources/views/backend/layouts/template.blade.php
@include('backend.layouts.header')
    @yield('content')
@include('backend.layouts.footer')